retargeting:
  type: DexPilot
  urdf_path: omnihand/omnihand_right.urdf

  target_joint_names: [ 'R_thumb_roll_joint', 'R_thumb_abad_joint', 'R_thumb_mcp_joint',
                        'R_index_abad_joint', 'R_index_pip_joint', 'R_middle_pip_joint',
                        'R_ring_abad_joint', 'R_ring_pip_joint', 'R_pinky_abad_joint', 'R_pinky_pip_joint' ]
  wrist_link_name: "base_link"
  finger_tip_link_names: [ "R_thumb_tip", "R_index_tip", "R_middle_tip", "R_ring_tip", "R_pinky_tip" ]
  scaling_factor: 1.0

  low_pass_alpha: 0.2
